import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Header } from './components/header';
import { Footer } from './components/footer';

const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'EShop NextJS14',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning={true} lang="en">
            <body suppressHydrationWarning={true} className={roboto.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
